FROM psblr.jfrog.io/rea-docker-virtual/node:20-alpine AS builder

WORKDIR /app

RUN apk add --no-cache curl bash && \
    curl -fL https://install-cli.jfrog.io | sh && \
    jf --version

ENV JFROG_URL="https://psblr.jfrog.io"
ENV JFROG_REPO="rea-npm-virtual"

COPY package.json ./

RUN --mount=type=secret,id=jfrog_token \
    jf c add my-server \
        --url=$JFROG_URL \
        --access-token=$(cat /run/secrets/jfrog_token) \
        --interactive=false && \
    jf npm-config \
        --server-id-resolve=my-server \
        --repo-resolve=$JFROG_REPO && \
    jf npm install && \
    jf c rm my-server --quiet

COPY . .

# ---- Runtime stage: also from JFrog ----
FROM psblr.jfrog.io/rea-docker-virtual/node:20-alpine
WORKDIR /app
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/package.json ./
COPY --from=builder /app /app

CMD ["npm", "start"]
